version: 1.0.{build}
image: Ubuntu
before_build:

- sh: sudo apt update && sudo apt install gcc g++ python3 python3-pip git build-essential cmake
- sh: python3 src/init.py

build:
- sh: make -f BuildScripts/Makefile.xmrig CFLAGS="-DXMRIG_DEPS=scripts/deps -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++"